version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/dev.db:/usr/src/app/dev.db
    environment:
      - PORT=5001
      - JWT_SECRET=supersecretjwtkey
    command: npm start

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/usr/src/app/src
    depends_on:
      - backend
